name: 사용자 피드백
description: Re:Answer 프로토타입을 사용한 뒤 간단한 피드백을 남겨주세요.
title: '[피드백] 주요 의견'
labels: [feedback]
body:
  - type: input
    id: name
    attributes:
      label: 이름 또는 닉네임
      placeholder: 예) 유진 / 민수
    validations:
      required: true

  - type: textarea
    id: good
    attributes:
      label: 좋았던 점
      placeholder: 어떤 점이 인상적이었나요?
    validations:
      required: false

  - type: textarea
    id: bad
    attributes:
      label: 아쉬웠던 점
      placeholder: 불편하거나 헷갈렸던 부분이 있었나요?
    validations:
      required: false

  - type: textarea
    id: idea
    attributes:
      label: 개선 아이디어
      placeholder: 이런 기능이 있으면 더 좋겠어요!
    validations:
      required: false
